<a href="https://colab.research.google.com/github/ssrakuen/skripsi-notebook/blob/main/Resnet_Models_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install tensorboard
!pip install gputil

  Preparing metadata (setup.py) ... done
  Created wheel for gputil: filename=GPUtil-1.4.0-py3-none-any.whl size=7394 sha256=4be501e5946765676725c697273d3cca4071ef4a2114792f8b8e2720f5b43f4a
  Stored in directory: /root/.cache/pip/wheels/a9/8a/bd/81082387151853ab8b6b3ef33426e98f5cbfebc3c397a9d4d0
Successfully built gputil


In [4]:
import os
import torch
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from torch.utils.data import DataLoader
from torchvision import transforms, datasets, models
import psutil
import time

# Function to load a model
def load_model(model_path, model_class):
    model = model_class(weights=None)
    model.fc = torch.nn.Linear(model.fc.in_features, 3)  # Adjust based on your number of classes
    model.load_state_dict(torch.load(model_path))
    model.eval()
    return model

# Function to test a model
def test_model(model, test_loader, device):
    y_true = []
    y_pred = []
    start_time = time.time()
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            y_true.extend(labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())
    end_time = time.time()

    # Metrics
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')
    conf_matrix = confusion_matrix(y_true, y_pred)

    # Resource usage
    process = psutil.Process(os.getpid())
    cpu_usage = process.cpu_percent()
    gpu_usage = torch.cuda.memory_allocated(device) / 1024**2  # GPU memory usage in MB
    memory_usage = process.memory_info().rss / 1024**2  # Memory usage in MB

    # Time used in seconds
    time_used = end_time - start_time

    return {
        'confusion_matrix': conf_matrix,
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'cpu_usage': cpu_usage,
        'gpu_usage': gpu_usage,
        'memory_usage': memory_usage,
        'time_used_seconds': time_used
    }

# Define device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Define data transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Load the test dataset
test_dataset = datasets.ImageFolder(root='/content/drive/MyDrive/Machine_Learning/Datasets/sleep_pose_dataset/A2/test', transform=transform)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Define directory paths for saved models
models_dir = '/content/drive/MyDrive/Machine_Learning/modelsA2/'

# List all model files in the directory
model_files = [f for f in os.listdir(models_dir) if f.endswith('.pth')]

# Dictionary to map model filenames to their respective classes
model_classes = {
    'resnet18': models.resnet18,
    'resnet34': models.resnet34,
    'resnet50': models.resnet50,
    'resnet101': models.resnet101,
    'resnet152': models.resnet152
}

# Dictionary to store test results
test_results = {}

# Iterate over each model file and test it
for model_file in model_files:
    model_name = model_file.split('_')[0]
    model_path = os.path.join(models_dir, model_file)

    print(f'Testing {model_name} model from {model_file}')

    # Load model
    model_class = model_classes[model_name]
    model = load_model(model_path, model_class)
    model.to(device)

    # Test model
    result = test_model(model, test_loader, device)
    test_results[model_file] = result  # Use model_file as key to distinguish between models

# Display test results
for model_file, result in test_results.items():
    print(f'Model File: {model_file}')
    print(f'Confusion Matrix:\n{result["confusion_matrix"]}')
    print(f'Accuracy: {result["accuracy"]:.4f}')
    print(f'Precision: {result["precision"]:.4f}')
    print(f'Recall: {result["recall"]:.4f}')
    print(f'F1 Score: {result["f1"]:.4f}')
    print(f'CPU Usage (%): {result["cpu_usage"]:.2f}')
    print(f'GPU Usage (MB): {result["gpu_usage"]:.2f}')
    print(f'Memory Usage (MB): {result["memory_usage"]:.2f}')
    print(f'Time Used (s): {result["time_used_seconds"]:.2f}')
    print('\n')


Testing resnet18 model from resnet18_lr0.001_batch16.pth
Testing resnet18 model from resnet18_lr0.001_batch32.pth
Testing resnet18 model from resnet18_lr0.001_batch64.pth
Testing resnet18 model from resnet18_lr0.0001_batch16.pth
Testing resnet18 model from resnet18_lr0.0001_batch32.pth
Testing resnet18 model from resnet18_lr0.0001_batch64.pth
Testing resnet34 model from resnet34_lr0.001_batch16.pth
Testing resnet34 model from resnet34_lr0.001_batch32.pth
Testing resnet34 model from resnet34_lr0.001_batch64.pth
Testing resnet34 model from resnet34_lr0.0001_batch16.pth
Testing resnet34 model from resnet34_lr0.0001_batch32.pth
Testing resnet34 model from resnet34_lr0.0001_batch64.pth
Testing resnet50 model from resnet50_lr0.001_batch16.pth
Testing resnet50 model from resnet50_lr0.001_batch32.pth
Testing resnet50 model from resnet50_lr0.001_batch64.pth
Testing resnet50 model from resnet50_lr0.0001_batch16.pth
Testing resnet50 model from resnet50_lr0.0001_batch32.pth
Testing resnet50 model 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Testing resnet101 model from resnet101_lr0.001_batch64.pth
Testing resnet101 model from resnet101_lr0.0001_batch16.pth
Testing resnet101 model from resnet101_lr0.0001_batch32.pth
Testing resnet101 model from resnet101_lr0.0001_batch64.pth
Testing resnet152 model from resnet152_lr0.001_batch16.pth


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Testing resnet152 model from resnet152_lr0.001_batch32.pth
Testing resnet152 model from resnet152_lr0.001_batch64.pth
Testing resnet152 model from resnet152_lr0.0001_batch16.pth
Testing resnet152 model from resnet152_lr0.0001_batch32.pth
Testing resnet152 model from resnet152_lr0.0001_batch64.pth
Model File: resnet18_lr0.001_batch16.pth
Confusion Matrix:
[[12  0  6]
 [ 0 18  0]
 [ 0  3 15]]
Accuracy: 0.8333
Precision: 0.8571
Recall: 0.8333
F1 Score: 0.8308
CPU Usage (%): 0.00
GPU Usage (MB): 64.33
Memory Usage (MB): 1137.38
Time Used (s): 11.08


Model File: resnet18_lr0.001_batch32.pth
Confusion Matrix:
[[18  0  0]
 [ 0 18  0]
 [ 0  0 18]]
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
CPU Usage (%): 0.00
GPU Usage (MB): 64.45
Memory Usage (MB): 1137.38
Time Used (s): 0.45


Model File: resnet18_lr0.001_batch64.pth
Confusion Matrix:
[[18  0  0]
 [ 0 18  0]
 [ 0  0 18]]
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
CPU Usage (%): 0.00
GPU Usage 